[gcp_credentials_json]
type = "service_account"
project_id = "stock-analysis-461503"
private_key_id = "be84fc45e5244a4b93f41921e724d1f0b4813da6"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC67DRyLhLZ8BSW
vz+EW93ZD/1KSUtqY/FuiaC0DRBVxDqmJwgHsOvpuI+FeTHleil4TstKslyxq3L+
pzeajozX+1PJT99a1yMWCGtZnjylyWaevAU+U6iSsvFL+KwOHoVLIZqIxsGCQUZF
gcQubr09xwLH5CG5Ti4rhEiEAIP3aYUE1eyGAN1n46vvEUfDEFioPtC60ug3aX15
erBk12CsV1f/yah9QJzB5ZiYTvMbdEZTgnIzghNd8U7ZSzODJa9mRsRseCzMDVLJ
duSxgAoBjXCBCp0gBdqe7zuqTTv8nfx7p0PeV+KYUfnmtaMxLC98uvHSJ1NwL2Xc
eb6wMRdhAgMBAAECggEAHZ5M5yS+zvK4SHSwa1glLH5Ym7tGbGq+uE2tfaouQvDP
fEFmB9X0Y7nfX/5mth5n0MzncIQXpP1uQMSdTmu1DIoh6h2yXhIF2LlnzTECGiDy
Fkfjqs8VwH0DOA8EsE4Mv+1or7CSvAF80Ymw3MymRtIwch0HbPXi4flZhjUQtBSq
I4oDi3KTL3AdvcqBbSbeUYOhhj68RU1SauyxKdH8l0OEgWTmSwkHst3caXXpn12Y
0ZyQfsWDNw8cbLNt9mgCujMmIneIr0fIKbi5e5X2DiJ5c+Q7gJ5WEruBaKCmtl0m
4HldXJkVa70GSuMvPR297tN9oZGsHTwkdHoejBpMCwKBgQDwHByEWWrfGkoniOsM
4/54dVjrmq/QNTBemXbqQLjWtj+M7BzI6GcUwr6f34FCxtogDRUSmbV+mEObkbdL
i8GJEzygZ5AYVgqY68NYlCNYXGreU+R6EVNREeBXMhGQ9MTAuFdMFOZ70nELF1td
9ZskaPes4pdJOoGDV/rYDCvNCwKBgQDHSwItjWd4toL+OEQBHrCP7zRcnhDplnqN
48vPvieG3H0xcm2WNLxGlbavxLCr0xlf5PF7Rt6EEY/iS7w4e/iTrQ9VhI0VzyEA
EBfTvwHotAYxumz9YVwmyvt83aaDrFS1w2FgWYxe07jfVKKI+CS7olDJLj7bHTSn
QDttbty4wwKBgHqqUeNHbzLFUob6CuMOAy30/VV4NEOROMHLcxXftM50Uukiot38
5NSVXR995qJ/xmXDaTWUc0VWcouimNqublQiEMH9xn64TjerkqPJInl81Vf50eqO
uVrcYBkLyi+c7HtscaS7tLgjXX8GErZgyD6EpaucIx/VFN9N7ie7qBDbAoGBAL5w
Fc+znNmEBh6pY4pyaiPQX4fVX7HmooutztdgDONZFKTIhKGRGQyWCbFiUbSPj2LM
Ilk7umwXYBfNaTnMdRegutNsS2k4uX8W4b3sewWD6ZthWr6xZ16GftSt9W1Dotrh
rc5lI7aFuNZoSLx76pYGIA5ui4/UE7lyrpb+5hoDAoGACbG/8EHbgbQ3KIBoV4nu
Hx/bH8xB9EUV58OROhjgZoJ5El41g19MlymELA/iRs9Z/oqIlJ1J2kXE4lnkF0eB
vC/BtdIS1M60qhJH2EfpDSqH+ku/R19hJcSIIjm1UNb+Xikt3fje1LZjuQe5A9PM
KHQb0Fzufh12UTcjQ87AJU4=
-----END PRIVATE KEY-----
"""
client_email = "streamlit@stock-analysis-461503.iam.gserviceaccount.com"
client_id = "111744637712091287420"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit%40stock-analysis-461503.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
