[gcp_service_account]
type = "service_account"
project_id = "stock-analysis-461503"
private_key_id = "f6ff3dfb9f503434afae222b5dd4c4cb98fdc5a1"
private_key = '''-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCZI/WKjNmI4EB2
vOmnSKkFJsiGIDV7KEUBd4I/2UW5WWDzZnVDljG6Bi0QPdkuOToZcgNjmG5Nl4Eb
dx3md+79ly1K1S1bkiuN//n4VpM2DyGsOtQLaSEm55Q3bcDMEu/M8MFxCip5O3Jd
B4jqpYKqosmP0lta4zUbVnLm0OS53A40r+TM6UZ2W3TxU6n1jZmn2uMJQTHeYICS
YOOjmXQct53olFu2mDbS0xU7yKVx3baF4M9bt8S6rMXC1WRFlxMKQkOc8zcHGxuT
PwIHVPLUWz1SCh4slCjOVmWVF7ZK6JBobOHmyxv5iV51BeqFzZRnTYzUQDO3icpS
d16bf5BXAgMBAAECggEAJs0KoJExaNHQ44TX+q+ZS5nZAsrUYiEA4u9BzCWj2eOA
ggs6uOYsMULxVgUlquWLB/lwTGLJx9UUPD5BECzhG9Wa/zPmKyZs7KynzDk7UV4i
HP5GzaFUagQQ9L5VNB+0LIvvp1F5E4BxaIrJMRLAebWHNm6JAQ1CXmvX7w2Mdl6b
dpC5KFjywgQpALRJtnwh19HjpOy5ESUf6iMtOu0yAsvzsZr45cuxT+iF+T/YTVvQ
qise2q73U+O3/f9dPPNyzJTUvg+Jl5E+JoFaoBSz8eza1C08oQ7S5iAlLy3x2xh+
hB03NYyKce3yhsNvrE7MunwaNL//n1AXVttZ3xpSwQKBgQDXUymW9CzUlGiihBIa
0HG1c8HCMaNbOo0qfDaxbw2uFUCLsBzgGUQtbEAT3eaMqUo+XXIkg/+ulrl4E5ax
+5O9KJl54VIMLcDUKFSia7NNfOO1NJ20xYQXB3GKegmM4K5wPV7iyQjmhUpRG/wn
sxvhV31yDDQK6wDyycv33XQEoQKBgQC2EaNqbcFwN9aP72b8PUz5ZxYhVqW3d/3u
wey5AqJsEiJgty8/C2mKtaaaKyYEC2BUpxoetGq1SvRuQ+AIO/kSUtN8/RISXXqw
oJ7nr/4GPlcZGKiaVOzjbx/Cdtit9GOiYvYEn66RTTRMp5aqg6i55w2H59GhaseM
ZFoMvv959wKBgFnM8RdnlhrCGjFM61ALhqCqOjCHCx3M+Xqyewzcx9PGQTkApcpA
P1LCRqcCcFhRcgk4Z5YbBtMFQSx23u4zgZXuDLPr6I/ztOvGNiXWzNyQLVcxLmRp
y4DfNdcOtlTuj1F4Bs6GERQymp/hD/Rumj4MguDBfiLfh3G5/zrMPMqBAoGALQkx
5fqeNbbqMRJj5BL5vlt8guSe+0IIIw3/E0iOirL1o/zMCAk3oyMJwerYbXmu62Gm
OWAhYRTYX4oUmZTUKG8qdylWVgqfdZ9VjzPeXwb+nmuWEQ7exedP8NdbA7SHDLzz
4/LnyHNTc36k6yrECrAXjb2PAiGamKSeDbcVFMMCgYEAiMGdFmeBCwdsvDUfzzgy
Riel8WiezQpbO0O+HDOhA+ceKQNxasV8YEqc9MHOojZ+F0yjjKcJwSkIEB1GJsZI
L/ZIpsuRvBpOJrgiJSDYg6k4HldG24qknlnxIm6gl7JDvbsdapeQVosOXKu1KAHI
v4L2zvnMUWhTZxNUsBx0y1M=
-----END PRIVATE KEY-----'''
client_email = "streamlit@stock-analysis-461503.iam.gserviceaccount.com"
client_id = "111744637712091287420"
auth_uri = "https://accounts.google.com/o/oauth2/auth"   
token_uri = "https://oauth2.googleapis.com/token"   
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"   
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit%40stock-analysis-461503.iam.gserviceaccount.com" 
